### ISSUE TITLE
Postgresql container is deprecated

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/ms_perfs#16]
switch to https://hub.docker.com/r/camptocamp/postgres/tags/

https://github.com/camptocamp/ms_perfs/blob/master/docker-compose.yml#L2

**Comment by yjacolin** [comment]
Pour https://github.com/camptocamp/ms_perfs/blob/master/docker-compose.yml#L7-L8 voir 
```
command: ["PG_SYSTEM_SHARED_BUFFERS", "256MB", "PG_SYSTEM_MAX_CONNECTIONS", "200"]
```

Retrouver les bons paramètres pgsql pour le paramètre command: --shared-buffer par exemple.

**Comment by pvalsecc** [comment]
On other projects I have stuff like that in the composition:
```
    command:
    - postgres
    - --shared_buffers=2GB
    - --max_connections=300
```
