### ISSUE TITLE
[summary] QGIS2 and 3 line in graph are not shown for last user number

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/ms_perfs#22]
Same for all layer:
![spectacle z25491](https://user-images.githubusercontent.com/660191/32449631-688a4e5a-c312-11e7-9f1d-978348e0c79a.png)

**Comment by pvalsecc** [comment]
I suspect that we don't have any successful request for it. Look at the errors section in the CSV.

**Comment by yjacolin** [comment]
if you select only QGIS 3 or QGIS 2 we get all the graph!
